language: go
go:
- '1.9'
gobuild_args: -x -ldflags "-X main.GitCommit=$TRAVIS_COMMIT"
before_install:
- go get -u github.com/labstack/echo/...
jobs:
  include:
  - name: Testing
  - stage: build
    name: Build binary for linux
    script: GOOS=linux go build -ldflags "-X main.GitCommit=$TRAVIS_COMMIT" -o server-linux
  - name: Build binary for macOs
    script: GOOS=darwin go build -ldflags "-X main.GitCommit=$TRAVIS_COMMIT" -o server-macos
deploy:
  provider: releases
  api_key:
    secure: cWv966YogqUK4YF0/KgnH3I42cQG481R6cPXnZHTiGop7x/tSW4CTGRqA+hkypVgtPGKqc8MHPcx2BDWSz46fmdCBZI2cg49YL02clQOVUDmtSUJmRoHOf9t+UE6tLUpXykbBVMEdgIAFI8XADz1YHIxPZG9rykYf/2r3tULsUX0Mwyr8pR05FdP9IsbknCrEylVZr6iCeGD9pCG4TqY/3yNGBvAFkJ1LxmDCc5CYcP7oNKsLuNTzSaxdzMlGYwdZ5C3FvxqSllmECLFd2Flp51ogB6lN86TYAcTAFVz8UUY8ZS8yJ6EU3mrJT7wz9O4qE8LO86HYX639Py/EmKqls20a0Vj5mF1gzzGLRheUNb6fiWdT2BaWst6Dp4waHaGxu56WspI1eGXlpUDSdRjVKBr1K/RN4pT0AhIc6KMFANocO5Pj+P2sarFWTfE0pLswIELjnDjytDkL5W5XAHeOnzEtksHEp1eBlrJmoyYda6rW5cf9dskodIYZRtxx03vL8Sxdrd1C3aRz3aE+pzTNhkzxu2chti2jKmvWFvuOqTw/roEgynoxXVZNP5msfHexDPHxCmIA5pLuUOhsyMdYX9q3TXYMXUMRSdof+qB+ltkPPpw0ZyAKbGbIdQuoGzyPMyZ6BSuU7jttRPtNOVEqozOoZJBvBU8+ZqP/xCPezQ=
  file: devops-app-aws
  on:
    repo: javiermarques/DevopsAppAws
