language: go
go:
- '1.9'
gobuild_args: -x -ldflags "-X main.GitCommit=$TRAVIS_COMMIT"
addons:
  apt:
    packages:
    - unzip
before_install:
- go get -u github.com/labstack/echo/...
- go get github.com/stretchr/testify/assert
jobs:
  include:
  - name: Testing
  - stage: build
    name: Build binary for linux
    script: GOOS=linux go build -ldflags "-X main.GitCommit=$TRAVIS_COMMIT" -o server-linux
  - name: Build binary for macOs
    script: GOOS=darwin go build -ldflags "-X main.GitCommit=$TRAVIS_COMMIT" -o server-macos
  - stage: ami
    name: Create AWS AMI with packer
    script: "./packer.sh"
  - stage: infra
    name: Apply infra changes
    script: "./terraform.sh"
deploy:
  provider: releases
  api_key:
    secure: cWv966YogqUK4YF0/KgnH3I42cQG481R6cPXnZHTiGop7x/tSW4CTGRqA+hkypVgtPGKqc8MHPcx2BDWSz46fmdCBZI2cg49YL02clQOVUDmtSUJmRoHOf9t+UE6tLUpXykbBVMEdgIAFI8XADz1YHIxPZG9rykYf/2r3tULsUX0Mwyr8pR05FdP9IsbknCrEylVZr6iCeGD9pCG4TqY/3yNGBvAFkJ1LxmDCc5CYcP7oNKsLuNTzSaxdzMlGYwdZ5C3FvxqSllmECLFd2Flp51ogB6lN86TYAcTAFVz8UUY8ZS8yJ6EU3mrJT7wz9O4qE8LO86HYX639Py/EmKqls20a0Vj5mF1gzzGLRheUNb6fiWdT2BaWst6Dp4waHaGxu56WspI1eGXlpUDSdRjVKBr1K/RN4pT0AhIc6KMFANocO5Pj+P2sarFWTfE0pLswIELjnDjytDkL5W5XAHeOnzEtksHEp1eBlrJmoyYda6rW5cf9dskodIYZRtxx03vL8Sxdrd1C3aRz3aE+pzTNhkzxu2chti2jKmvWFvuOqTw/roEgynoxXVZNP5msfHexDPHxCmIA5pLuUOhsyMdYX9q3TXYMXUMRSdof+qB+ltkPPpw0ZyAKbGbIdQuoGzyPMyZ6BSuU7jttRPtNOVEqozOoZJBvBU8+ZqP/xCPezQ=
  file:
  - server-linux
  - server-macos
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: EY0o2zFtqYgFHiaWLpYAiCZHNNpSDaD8IYQVZjciEvBqLCKrNtYxEpildnMp1realk3H7vGYJbU0FqO8PlhZmFrxnGkj5G/DWZEcA7mYBdvBNtyJ/6HFzP3NpnRCaaZJxecUqwLYM34HUo1EmArFoCYhdQ6K5/cZ0fA8GxpcIwhl2uhLe3HNJaQrdTFiLxZ7THce7NabxqVWD2nQRlsLIZPPMPXR4Cvbvq3Mpy8mskIBHGhy9BGGSSvUUKEUViKqwzy2DYM0HdNWWOo6ff9p+PkS491z8x0NR4dhKVtVms4qrHSyJGdCg4Eacd4pilJMQpaGgCPYorI5z3+bAyt0suva0C3pTkGuCkAw4FOM3telLiGfiWpisq+p3DSfc8mzUoZW1en0RCNpVPZfxnw9QNDwBjsCinK91/NgeQyoKXoC1lUD5VWzLZIhOI4lw7iMV4t4caI+x0xyKJq2SErTsrwFNKhJ9vhz3xexAF3YaPieztDwBVyynGOxkk8iJaBTB1SRa3dskpC3Nm1GyIUAHJkg2QipXGNWwM/hrv8dsYX+J1cS7MPg7fXgAzATrlYeRcqZlSpC+39PqI/dBJqtaSONSVrhzB9IFalj4S7beA7lUQ/Qwv3Dk+dS5duFG7om6Rh+J9RurC1Z92ghk9BrJNaTU2JFe2RIxj5TnqysdCA=
  - secure: Sfx8pEya2GWAwWbceVywcmF0Nx0amDZ41LPpsUb2XQ3FYWIts1mWMuy+fQfcbjtoDORpcwJL5+giKM4numUKDwZLEqsw1CL1HzYf22M1S4ACcWRxCBPbiv4MJhnjC5GDItG9AobzBJhefxMoeKQ9CiNTpfzeQ0/5YR1IROiVvJFNpfOoSZZMGVKk3HiIOEzm3ajM/Ve6y45I4qF7Pn+bsmQt1beUXJcbFih6euCpjQJnBqkzQR6Tp+50I1fs7SmZDQhHhUgBn9E4R3f20bnSGUItgF30DC/TZMgkn8abzKu1I8WH+vFkqeh+kpS92DAmS8nEEhcvCZ9wff+nwB+Xch6zqAIrWgg6EZiKfF9gbadFz5UO9XigP6IHTq3MFOCUjPhmNFYwrVhwSfW9ABYcr5FM7L6jDsLYcjOhAwtRReMgHyUoEcFLM4Nhk/MRWtA3okUG91r1Ila2/GAkTNeXTHjxonv5JJ4BF/Gz6nq+2avENBNGloAwvixz/AgqSZ2fsz3JAJjwMzCRgtH/ugXyZ66gH5ZRWMzzmr8QZROIlO5JkOwZCX9jWgUbE2m9a2NPFOapt03+iO9Xcays8V7OplLt2sJjKJJfoXLmwVwlia1MMyIl4pe0EpsTM21vhtUTtuHRSeX/ccHyFztG0LDLUoosGvtj3o7sOjgv9Znp71A=
