language: go
go:
- '1.9'
gobuild_args: -x -ldflags "-X main.GitCommit=$TRAVIS_COMMIT"
addons:
  apt:
    packages:
    - unzip
before_install:
- go get -u github.com/labstack/echo/...
jobs:
  include:
  - name: Testing
  - stage: build
    name: Build binary for linux
    script: GOOS=linux go build -ldflags "-X main.GitCommit=$TRAVIS_COMMIT" -o server-linux
  - name: Build binary for macOs
    script: GOOS=darwin go build -ldflags "-X main.GitCommit=$TRAVIS_COMMIT" -o server-macos
  - stage: ami
    name: Create AWS AMI with packer
    script: "./packer.sh"
  - stage: infra
    name: Apply infra changes
    script: "./terraform.sh"
deploy:
  provider: releases
  api_key:
    secure: cWv966YogqUK4YF0/KgnH3I42cQG481R6cPXnZHTiGop7x/tSW4CTGRqA+hkypVgtPGKqc8MHPcx2BDWSz46fmdCBZI2cg49YL02clQOVUDmtSUJmRoHOf9t+UE6tLUpXykbBVMEdgIAFI8XADz1YHIxPZG9rykYf/2r3tULsUX0Mwyr8pR05FdP9IsbknCrEylVZr6iCeGD9pCG4TqY/3yNGBvAFkJ1LxmDCc5CYcP7oNKsLuNTzSaxdzMlGYwdZ5C3FvxqSllmECLFd2Flp51ogB6lN86TYAcTAFVz8UUY8ZS8yJ6EU3mrJT7wz9O4qE8LO86HYX639Py/EmKqls20a0Vj5mF1gzzGLRheUNb6fiWdT2BaWst6Dp4waHaGxu56WspI1eGXlpUDSdRjVKBr1K/RN4pT0AhIc6KMFANocO5Pj+P2sarFWTfE0pLswIELjnDjytDkL5W5XAHeOnzEtksHEp1eBlrJmoyYda6rW5cf9dskodIYZRtxx03vL8Sxdrd1C3aRz3aE+pzTNhkzxu2chti2jKmvWFvuOqTw/roEgynoxXVZNP5msfHexDPHxCmIA5pLuUOhsyMdYX9q3TXYMXUMRSdof+qB+ltkPPpw0ZyAKbGbIdQuoGzyPMyZ6BSuU7jttRPtNOVEqozOoZJBvBU8+ZqP/xCPezQ=
  file:
  - server-linux
  - server-macos
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: U8yX4CK4R/7of+Q9d+1pcsu2ijcSK1MVfZRIgfaRWkzJtURi3sC5dIRfc/7Yn/XZqlXJkW4L2XWo0cAiR906Oe8HxeJngtf3jqT4SzaJS8ddryGU0V1gBmwIuj4I3+vSUL/dd1rbHHZ91zegr+fwD3qpK9CzghzEhlAiqa/HIqt1z1BNm75kG34ijeFegWwO3fn9mVmo8qJ1MMX0TgDDs56SMoxQoFyuEyoVmT0AmKww5hh7FN2THjnlbIOP1QUiUjDYmx0GE4/Q+h7w1f731EpTxAJdccl8TrwG7PvQMbIbErV+lQypEVv9KBcGuq280MlpuxHGSLVz/V3Y2yv8HXj0rXOiVYp4AFI23N7pMUONfGH4Ol7+sSJKvgH2OI55JJZtFODHIeSaG16QDvCJpRKp9z1wNS4Goj+ks0QkdQh+/icT04MjD5rt80WjIt6ANp4PNAIXwtq7adiCG9bigD6zf/Es2a2xzPM7UjDk92OTFSEyuAT5Sc6US2lzVbuHOS3qPCe6EDbaYZocoAT49nvF11V7kO0OLrHM7QRe7gUj4DIQqY4MKMBSWwGTSeGspDXA/RrATltGneFBgiofjJDkC08JpjRN6aOesrh7RgFPMqMlr7ZcSZyEoKF6XuW6I/smyq6VGgprF0UFyp7FbngKVKCmoiYQ9AUn2ac2e4M=
  - secure: AR7Tx7f/4IIgMNnh/f6ESU/wLFyz7hHPFoVdpGpFY27UHKQC13X/K0pyIBJbUpMDghFMMT8eSfMb2M1GSEYOlGo32TVQyjyH1pHJJ2O8Anhj6fLzW4Xup5331FbKzk9HY9MNWGZntzqR5oKc6QF85FP08iq+CdLmFauByWi9xPze4Pve5ZD6C6V2443ztPs8tGv/FXkNUTNDCD6qVRIzkuY8L1sSJlmaZWF8+S6ZQikyeC0aip1RvOLkqukjRCu2av8Ue/o+x9Ym7Xn3zi1cmJN58/KbdTu+lgD548/gy5ExrMxZAiewygMOKDFyJMnUooUno2UFKmyDjtuCpyA5pOyY294ncvcTO5oKy6mYO9wtkpNKZH5O8kvzunQxYLeC6CZNlPT9jsL7GIIp7Bugp9CCcf6e/19e+GYB4nvOtgcBX/wHInzRBpOwVwiiWYGCL655ns/VtiusssJjk8ZWhoauOZ0AuaHhV76xF+W3CM7UWY5sXpGIbfJj216QUw6+04vTgvwA5yVqjvLCaHhZ/Ilbp4hIsfH5w1fWQqQRvr95kW8ZXYPLemeTO/KnkpAKvZUtaKnGbXcoqFF9mmHT0bDfN+q0NGvwxsZgTq0vS/E54KBXI1ukHCru3AVxMgm2bNpX3+TY4XI4KyF39ePTAVu9zxC0pv6pIAs4Es2+fIg=
